// src/game/config/mosquitoes.config.ts
import { MosquitoConfig } from '../types/mosquito.types';
import { MosquitoType } from '../types/game.types';

export const MOSQUITO_CONFIGS: Record<MosquitoType, MosquitoConfig> = {
  NORMAL: {
    name: 'ยุงธรรมดา',
    baseHp: 40,
    hpPerWave: 25,
    speed: 0.9,
    reward: 15,
    size: 10,
    color: '#a3e635',
    bossDamage: 1,
  },
  SPEEDY: {
    name: 'ยุงเร็ว',
    baseHp: 24,
    hpPerWave: 15,
    speed: 1.6,
    reward: 20,
    size: 10,
    color: '#38bdf8',
    bossDamage: 1,
  },
  TANK: {
    name: 'ยุงอึด',
    baseHp: 100,
    hpPerWave: 60,
    speed: 0.6,
    reward: 35,
    size: 14,
    color: '#f97316',
    bossDamage: 1,
  },
  BOSS: {
    name: 'บอสยุง',
    baseHp: 200,
    hpPerWave: 125,
    speed: 0.45,
    reward: 250,
    size: 18,
    color: '#ef4444',
    bossDamage: 5,
  },
  ARMORED: {
    name: 'ยุงเกราะ',
    baseHp: 80,
    hpPerWave: 50,
    speed: 0.8,
    reward: 30,
    size: 12,
    color: '#6b7280',
    armor: 30,
    bossDamage: 1,
  },
  STEALTH: {
    name: 'ยุงล่องหน',
    baseHp: 50,
    hpPerWave: 30,
    speed: 1.0,
    reward: 25,
    size: 10,
    color: '#8b5cf6',
    isStealthed: true,
    bossDamage: 1,
  },
  SPLITTER: {
    name: 'ยุงแบ่งตัว',
    baseHp: 60,
    hpPerWave: 35,
    speed: 0.9,
    reward: 25,
    size: 11,
    color: '#ec4899',
    canSplit: true,
    bossDamage: 1,
  },
};